-- ============================================================================
-- CLONE PROFILE 1 -> PROFILE 4  ·  STEP 2 of 3: COPY
-- ============================================================================
-- WHAT THIS DOES
--   Clones profile 1's training data onto profile 4 so the Engine v2 planner,
--   progression-state builder, dossier builder and gap-decay logic have real
--   signal to reason about. Data operation only — no application code, no
--   prompt changes, no v1 logic touched.
--
-- STATUS: **NOT RUN.** Written by Claude Code, executed manually by Shimmy in
--   the Supabase SQL editor. Never assume it has been run.
--
-- PREREQUISITES
--   1. Baseline query run and output saved (verification file, section A).
--   2. 2026-07-22_clone_p1_to_p4_wipe.sql run to completion, all counts 0.
--   3. Run this file top-to-bottom in ONE execution. Section 0 aborts the whole
--      run if profile 4 is not empty.
--   4. Section 9 (setval) is MANDATORY. Read its comment before skipping it.
--   5. Then run 2026-07-22_clone_p1_to_p4_flags.sql.
--
-- SAFETY CONTRACT
--   * Profile 1 is READ-ONLY throughout: it appears only in `SELECT ... WHERE
--     profile_id = 1` and `FROM profiles WHERE id = 1`. No INSERT, UPDATE or
--     DELETE in this file targets profile 1.
--   * Every write is explicitly scoped to profile 4 / `id = 4`.
--   * No unqualified DELETE. No `profile_id <> 1`.
--
-- ID STRATEGY — deterministic +100000 offset
--   Cloned rows take `id = source_id + 100000`. This makes parent->child
--   mapping pure arithmetic (exercises.workout_id + 100000), needs no temp
--   tables or RETURNING correlation, and makes the whole script reproducible:
--   a wipe + re-run produces byte-identical ids. Profile 1's max workout id is
--   ~110, so the offset leaves ~99,890 ids of headroom.
--
-- IDENTITY HANDLING — universal, resolves itself at run time
--   Some of these tables are `GENERATED ALWAYS AS IDENTITY` (daily_sleep,
--   daily_steps, body_metrics, workout_templates per their documented DDL),
--   others were created ad-hoc in the SQL editor and their identity kind is not
--   recorded anywhere in the repo. `GENERATED ALWAYS` refuses an explicit id
--   unless the INSERT carries OVERRIDING SYSTEM VALUE; serial / GENERATED BY
--   DEFAULT reject that clause. Each INSERT below is therefore built by a DO
--   block that reads information_schema and adds the clause only when the
--   column actually requires it — so the baseline query's result cannot
--   invalidate this script either way.
--
-- SKIPPED ROWS — the 6 malformed-date workouts
--   Profile 1 has 6 workouts whose `date` column holds a TIME STRING, not a
--   date (ids 110 "10:12", 97 "12:52", 95 "13:00", 88 "19:37", 82 "10:07",
--   77 "10:20"). This is a real production data bug — `workouts.date` is a TEXT
--   column, so these values stored without error. They are invisible to every
--   `date >= x` query in the app and have zero child exercise rows. They are
--   excluded here by a shape regex rather than by hardcoded id, so a 7th such
--   row appearing after the audit is also caught. There is NO hardcoded id list
--   in the filter — this matters, because profile 1 keeps growing (its workout
--   count moved 81 -> 82 between the API audit and the Section A1 baseline).
--   The clone therefore takes "however many date-valid workouts profile 1 has
--   at run time", which was 76 of 82 at baseline.
--   Profile 1's rows are NOT repaired and NOT touched. See ROADMAP.md §6.
--
-- COLUMN LISTS
--   workouts/exercises column lists were read off live production rows.
--   The others come from their documented DDL. If any column name is wrong the
--   INSERT fails loudly — it cannot silently drop a column's data.
-- ============================================================================


-- ── 0. GUARD — refuse to run against a non-empty profile 4 ──────────────────
DO $$
DECLARE n bigint;
BEGIN
  SELECT (SELECT count(*) FROM workouts          WHERE profile_id = 4)
       + (SELECT count(*) FROM exercises         WHERE profile_id = 4)
       + (SELECT count(*) FROM daily_sleep       WHERE profile_id = 4)
       + (SELECT count(*) FROM daily_steps       WHERE profile_id = 4)
       + (SELECT count(*) FROM body_metrics      WHERE profile_id = 4)
       + (SELECT count(*) FROM daily_checkins    WHERE profile_id = 4)
       + (SELECT count(*) FROM micro_goals       WHERE profile_id = 4)
       + (SELECT count(*) FROM workout_templates WHERE profile_id = 4)
    INTO n;
  IF n > 0 THEN
    RAISE EXCEPTION
      'Profile 4 still holds % cloneable row(s). Run 2026-07-22_clone_p1_to_p4_wipe.sql first. (Re-running the copy without a wipe would violate UNIQUE(profile_id,date) on daily_sleep/daily_steps/body_metrics/daily_checkins and duplicate the +100000 ids.)', n;
  END IF;
END $$;


-- ── 1. workouts ─────────────────────────────────────────────────────────────
-- wearable_activity_id is forced to NULL: it carries a UNIQUE partial index and
-- profile 1 had 46 non-null values at audit time (and may have more now), so a
-- verbatim copy is a guaranteed constraint violation. wearable_data IS kept — it holds
-- avg/peak HR, calories, zones and duration_minutes (real autoregulator signal)
-- and contains no credentials.
-- Dates are copied VERBATIM. Gap-decay, "stalled >3 weeks" and "untouched
-- >6 weeks" are all relative to today; shifting or compressing dates would
-- destroy exactly the signal this clone exists to produce.
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'workouts' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO workouts
      (id, profile_id, date, type, notes, done, mobility, med, ts,
       wearable_data, wearable_activity_id)
    %s
    SELECT w.id + 100000, 4, w.date, w.type, w.notes, w.done, w.mobility, w.med, w.ts,
           w.wearable_data, NULL
    FROM workouts w
    WHERE w.profile_id = 1
      AND w.date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
  $f$, COALESCE(ov, ''));
END $$;


-- ── 2. exercises ────────────────────────────────────────────────────────────
-- workout_id is remapped by the same +100000 offset. Rows with a NULL
-- workout_id (extract-exercises can insert one) copy through as NULL, which is
-- always FK-valid. The EXISTS guard means an exercise can only land if its
-- parent workout actually cloned — belt-and-braces against the 6 skipped
-- workouts (audit measured 0 exercise rows under them, so this should be a
-- no-op, but it makes the FK guarantee structural rather than assumed).
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'exercises' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO exercises
      (id, profile_id, workout_id, date, name, category, main_category, subcategory,
       sets, reps, weight_lbs, distance_miles, duration_minutes,
       notes, raw_text, created_at)
    %s
    SELECT e.id + 100000, 4,
           CASE WHEN e.workout_id IS NULL THEN NULL ELSE e.workout_id + 100000 END,
           e.date, e.name, e.category, e.main_category, e.subcategory,
           e.sets, e.reps, e.weight_lbs, e.distance_miles, e.duration_minutes,
           e.notes, e.raw_text, e.created_at
    FROM exercises e
    WHERE e.profile_id = 1
      AND (e.workout_id IS NULL
           OR EXISTS (SELECT 1 FROM workouts w4
                      WHERE w4.id = e.workout_id + 100000 AND w4.profile_id = 4))
  $f$, COALESCE(ov, ''));
END $$;


-- ── 3. daily_sleep ──────────────────────────────────────────────────────────
-- The substitute for live readiness on profile 4 (which has no wearable
-- connection, by design — see the Phase 1 audit, open question 3, option (a)).
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'daily_sleep' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO daily_sleep
      (id, profile_id, date, hours, score,
       deep_minutes, rem_minutes, light_minutes, wake_minutes,
       hrv, rhr, source, created_at)
    %s
    SELECT s.id + 100000, 4, s.date, s.hours, s.score,
           s.deep_minutes, s.rem_minutes, s.light_minutes, s.wake_minutes,
           s.hrv, s.rhr, s.source, s.created_at
    FROM daily_sleep s
    WHERE s.profile_id = 1
  $f$, COALESCE(ov, ''));
END $$;


-- ── 4. daily_steps ──────────────────────────────────────────────────────────
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'daily_steps' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO daily_steps
      (id, profile_id, date, steps, calories, distance_miles, floors, source, created_at)
    %s
    SELECT d.id + 100000, 4, d.date, d.steps, d.calories, d.distance_miles, d.floors,
           d.source, d.created_at
    FROM daily_steps d
    WHERE d.profile_id = 1
  $f$, COALESCE(ov, ''));
END $$;


-- ── 5. body_metrics ─────────────────────────────────────────────────────────
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'body_metrics' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO body_metrics
      (id, profile_id, date, weight_lbs, body_fat_pct, bmi, source, created_at)
    %s
    SELECT b.id + 100000, 4, b.date, b.weight_lbs, b.body_fat_pct, b.bmi, b.source, b.created_at
    FROM body_metrics b
    WHERE b.profile_id = 1
  $f$, COALESCE(ov, ''));
END $$;


-- ── 6. daily_checkins ───────────────────────────────────────────────────────
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'daily_checkins' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO daily_checkins
      (id, profile_id, date, energy, soreness, severity, checkin_text, created_at)
    %s
    SELECT c.id + 100000, 4, c.date, c.energy, c.soreness, c.severity, c.checkin_text, c.created_at
    FROM daily_checkins c
    WHERE c.profile_id = 1
  $f$, COALESCE(ov, ''));
END $$;


-- ── 7. micro_goals (Active Challenges) ──────────────────────────────────────
-- NOTE: micro_goals.id is an INTEGER, not a uuid. CLAUDE.md and ROADMAP.md §2
-- both claimed uuid/gen_random_uuid(); live rows are ids 1 and 2. Docs
-- corrected in the same session as this file. It therefore takes the same
-- +100000 offset as every other table — no uuid regeneration.
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'micro_goals' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO micro_goals
      (id, profile_id, title, type, target_value, target_unit, period, end_date,
       current_value, is_active, created_at)
    %s
    SELECT m.id + 100000, 4, m.title, m.type, m.target_value, m.target_unit, m.period,
           m.end_date, m.current_value, m.is_active, m.created_at
    FROM micro_goals m
    WHERE m.profile_id = 1
  $f$, COALESCE(ov, ''));
END $$;


-- ── 8. workout_templates ────────────────────────────────────────────────────
-- Profile 1 was measured to have 0 templates (this also resolves the ROADMAP §9
-- open item: the Log-past panel's "only + New Template" was the CORRECT empty
-- state, not a render bug). Kept for completeness / future re-runs.
DO $$
DECLARE ov text;
BEGIN
  SELECT CASE WHEN identity_generation = 'ALWAYS' THEN 'OVERRIDING SYSTEM VALUE' ELSE '' END
    INTO ov
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'workout_templates' AND column_name = 'id';

  EXECUTE format($f$
    INSERT INTO workout_templates
      (id, profile_id, name, type, notes_template, exercises, use_count, created_at)
    %s
    SELECT t.id + 100000, 4, t.name, t.type, t.notes_template, t.exercises, t.use_count, t.created_at
    FROM workout_templates t
    WHERE t.profile_id = 1
  $f$, COALESCE(ov, ''));
END $$;


-- ── 8b. profile-row payload (profile_data + briefs + roadmap + body) ────────
-- profile_data is REPLACED WHOLESALE, never merged: profile 4 has its own 6
-- goals / 2 injuries / schedule, and merging would leave the v2 planner reading
-- 12 goals, half of them fictional.
--
-- Three identity keys are stripped on the way across, per the SKIP bucket:
--   - avatar_image  (profile 1's base64 photo)
--   - avatar_color
--   - name          (re-set to profile 4's OWN top-level name; the key must
--                    exist because fetchAI() hard-returns on a missing
--                    currentProfileData.name)
-- Everything else in profile_data comes over intact: goals (with their ids and
-- per-goal roadmaps), injuries, schedule, focus_override, ai_prompt_context,
-- equipment, philosophy, belt/martial-arts keys, settings.
UPDATE profiles p4
SET profile_data = (p1.profile_data - 'avatar_image' - 'avatar_color')
                     || jsonb_build_object('name', p4.name),
    coaching_brief              = p1.coaching_brief,
    historical_brief            = p1.historical_brief,
    historical_brief_updated_at = p1.historical_brief_updated_at,
    roadmap_data                = p1.roadmap_data,
    roadmap_data_updated_at     = p1.roadmap_data_updated_at,
    height_inches               = p1.height_inches,
    birth_date                  = p1.birth_date,
    sex                         = p1.sex,
    goal_weight_lbs             = p1.goal_weight_lbs,
    goal_weight_timeline_months = p1.goal_weight_timeline_months,
    gym_access                  = p1.gym_access,
    gym_type                    = p1.gym_type
FROM profiles p1
WHERE p4.id = 4 AND p1.id = 1;


-- ============================================================================
-- ── 9. MANDATORY: advance the shared identity sequences ─────────────────────
-- ============================================================================
-- READ THIS BEFORE SKIPPING IT.
--
-- These sequences are SHARED across every profile. The inserts above wrote ids
-- in the 100,000+ range without consuming sequence values, so each sequence is
-- still sitting at ~its pre-clone position. Left alone, profile 1's next real
-- workout/exercise/sleep row keeps drawing small ids — which is fine today, but
-- the sequence will eventually climb into the cloned range and collide with a
-- profile 4 row, producing a duplicate-key failure on a REAL user's save.
--
-- setval() to MAX(id) makes the next value land safely above every cloned row.
-- pg_get_serial_sequence works for BOTH flavours present here (confirmed by the
-- Section A2 baseline): plain nextval sequences on workouts/exercises/
-- daily_checkins, and GENERATED ALWAYS identities on daily_sleep/daily_steps/
-- body_metrics/micro_goals/workout_templates. All eight are covered below.
--
-- HARDENED AGAINST A SILENT NO-OP. setval() is a STRICT function: given a NULL
-- sequence name it returns NULL and does nothing, without raising. So if any of
-- these sequences is not OWNED BY its column (possible for a column defined as
-- `bigint DEFAULT nextval('seq')` rather than as a real `serial`),
-- pg_get_serial_sequence returns NULL and the "mandatory" step would quietly
-- skip that table — leaving exactly the future collision this section exists to
-- prevent, with no error to notice. The loop below RAISES instead, and prints
-- the new value for each sequence so the result is visible rather than assumed.
--
-- This section is idempotent and safe to re-run on its own.
DO $$
DECLARE
  t    text;
  seq  text;
  maxv bigint;
BEGIN
  FOREACH t IN ARRAY ARRAY['workouts','exercises','daily_sleep','daily_steps',
                           'body_metrics','daily_checkins','micro_goals',
                           'workout_templates']
  LOOP
    seq := pg_get_serial_sequence(t, 'id');
    IF seq IS NULL THEN
      RAISE EXCEPTION
        'No sequence found for %.id — setval would have silently done nothing, leaving the id sequence able to collide with cloned rows later. Resolve the owning sequence manually before treating this clone as complete.', t;
    END IF;
    EXECUTE format('SELECT COALESCE(MAX(id), 1) FROM %I', t) INTO maxv;
    PERFORM setval(seq, GREATEST(maxv, 1), true);
    RAISE NOTICE 'sequence % advanced to % (table %)', seq, GREATEST(maxv, 1), t;
  END LOOP;
END $$;
-- ============================================================================


-- ── 10. Quick sanity read (full verification lives in its own file) ─────────
SELECT 'workouts cloned'  AS what, count(*) AS n FROM workouts  WHERE profile_id = 4
UNION ALL SELECT 'exercises cloned', count(*) FROM exercises WHERE profile_id = 4
UNION ALL SELECT 'workouts skipped (malformed date — 6 known, see ROADMAP §6)',
                 count(*) FROM workouts WHERE profile_id = 1 AND date !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
UNION ALL SELECT 'workouts date-valid on p1 (should equal "workouts cloned")',
                 count(*) FROM workouts WHERE profile_id = 1 AND date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$';
